# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4839d4896126a0ef4a29fe306fed9e4a7fd753a9ebb9feabc77371e09c127c93dfea0f8623f353ed37fa7f7814ce9f3455312ecbd5ac6ab0eff30bccda776993

test:
  secret_key_base: 10c36ef8be036d1e8857c8f5fdd986c39e89b934f4ca7cb05e522730acfd6ce8e8d73584a059b3efcc61bcffc6c14535fac128f20ddf46d516aa57cbe3e273a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
